### ISSUE TITLE
Apiary picture is not saved at logout

### ISSUE THREAD

**Issue by lzpons** [mellisphera/mellisphera-web#168]
The apiary pictures (in "My Apiary" page) can be introduced either by drag&drop of a file or by using the "camera icon". Both of them are working properly to load a new picture but none of them is saving it at log out.

![Capture d’écran 2020-06-07 à 16 26 02](https://user-images.githubusercontent.com/41069288/83971480-963b6300-a8db-11ea-91ac-98acab8fe7c5.png)

when logging again the picture is not present
![Capture d’écran 2020-06-07 à 16 26 21](https://user-images.githubusercontent.com/41069288/83971485-a18e8e80-a8db-11ea-9781-b0b65f40fd1a.png)

Note that :
- No ERR messages are found in the Console
- No confirmation is given to user (not implemented)
- the files are stored locally on the server (folder defined by *application.properties* variable *mellisphera.app.img.pathServer=*) but there are no new files since may 27. Which would mean the process is broken since the last deployment. 
I have tried with 775 and 777 righs but has no effect neither.

To improve : 
- Control the image saving process / find what's not working currently
- send a confirmation to the user "you picture was saved" / "image enregistrée"
- add an error mesage (user/console/logfile-nohup ) in case something goes wrong

**Comment by savioarthu** [comment]
Check in the src/main/java/com/mellisphera/imgTool.java file (screenshot) : the path """server_path='apiwatch/production/imgClient/ """ no longer exists.
 
<img width="479" alt="Capture d’écran 2020-06-19 à 17 13 36" src="https://user-images.githubusercontent.com/49641714/85148356-5451db80-b250-11ea-9375-e4557cbd5d0e.png">

However, the correct path in applications properties (used with the value "${mellisphera.app.img.pathServer}") should be used instead of 'apiwatch/production/imgClient". Indeed, the new path is 'mellisphera/production/imgClient' (correct in the applications.properties file).
It seems that the '/apiwatch/production/imgClient' old path overwrites the new path (see the screenshot this.server_path = "/apiwatch/production/imgClient/").

**Comment by lzpons** [comment]
Partially solved with commit aa155d669e17d4efe5beaee0e32f2a05f073eb57 (22/06/2020 dev branch on mellisphera-api repo)

Files are properly stored on the server but up to a certain size. Higer size files ex 6Mb are not stored nor there is a warning to tell the user to make it smaller. 

Create a warning  to limit file size (behind the scenes files are also reduced)

**Comment by lzpons** [comment]
Need to introduce Message translation into json files on the /src/assets/i18n/
into the `"HOME" : {} section`

EN File can not be loaded : Max file size 5Mb
FR Le fichier ne peut pas être téléchargé : taille maximale 5 Mo
ES La imagen no se puede cargar : talla maxi 5 Mb

Take care of the drag&drop mode too !

Note that we changed the image folder test / prod
So in the java we need to set
`#mellisphera.app.img.pathServer=/mellisphera/imgClient.test`

**Comment by kasuntech** [comment]
fixed

**Comment by kasuntech** [comment]
fixed and PR created

**Comment by lzpons** [comment]
solved
